import { renderCustomSelect } from './components/_custom-select.js';
import { toggleBurgerMenu } from './components/_open-nav-menu.js';
import { moveNav } from './components/_move-nav.js';
import { openPopup } from './components/_nav-popup.js';
import { initPromoSwiper } from './components/_promo-swiper.js';
import { initCardsSwiper } from './components/_cards-swiper.js';
import { setPaginationSwiper } from './components/_pagination-swiper.js';
import { moveForm } from './components/_move-form.js';
import { setModals } from './components/_modal.js';
import { addScrollButton } from './components/_button-scroll-top.js';
import { addSideNav } from './components/_side-nav.js';
import { openVisibleFontCardContent, setAccordeonToggles } from './components/_accordion.js';
import { setFilterRange } from'./components/_range.js';
import { moveFilters, setFilterToggles } from './components/_filters.js';
import { setThumbSwiper } from './components/_thumb-swiper.js';
import { moveDetails } from './components/_move-details.js';
import { setTabs } from './components/_tabs.js';
import { setGridColumnLayout } from './components/_grid-layout-columns.js';
import { setNavigationSwiper } from './components/_navigation-swiper.js';
import { setCompareSwiper } from './components/_compare-swiper.js';
import { setStickyCards } from './components/_compare-sticky.js';
import { setFileInputs } from './components/_file-input.js';
import { hideLabel } from './components/_hide-label.js';

document.addEventListener('DOMContentLoaded', () => {
  renderCustomSelect();
  toggleBurgerMenu();
  moveNav();
  openPopup();
  setFilterRange();
  initPromoSwiper();
  initCardsSwiper();
  setPaginationSwiper();
  moveForm();
  setModals();
  addScrollButton();
  addSideNav();
  openVisibleFontCardContent();
  setAccordeonToggles();
  moveFilters();
  setFilterToggles();
  setThumbSwiper();
  moveDetails();
  setTabs();
  setGridColumnLayout();
  setNavigationSwiper();
  setCompareSwiper();
  setStickyCards();
  setFileInputs();
  hideLabel();
});
