import { renderCustomSelect } from './components/_custom-select.js';
import { toggleBurgerMenu } from './components/_open-nav-menu.js';
import { moveNav } from './components/_move-nav.js';
import { openPopup } from './components/_nav-popup.js';
import { initPromoSwiper } from './components/_promo-swiper.js';
import { initCardsSwiper } from './components/_cards-swiper.js';
import { initPaginationSwiper } from './components/_pagination-swiper.js';
import { moveForm } from './components/_move-form.js';
import { setModals } from './components/_modal.js';
import { addScrollButton } from './components/_button-scroll-top.js';
import { addSideNav } from './components/_side-nav.js';
import { openVisibleFontCardContent, setAccordeonToggles } from './components/_accordion.js';
// import { createRange } from'./components/_range.js';

document.addEventListener('DOMContentLoaded', () => {
  renderCustomSelect();
  toggleBurgerMenu();
  moveNav();
  openPopup();
  initPromoSwiper();
  initCardsSwiper();
  initPaginationSwiper();
  moveForm();
  setModals();
  addScrollButton();
  addSideNav();
  openVisibleFontCardContent();
  setAccordeonToggles();
  // createRange(0, 970, 1, 0, 900);
});
